# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('scheduled_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
